In [7]:
!pip install numpy
import numpy as np

In [8]:
#ndarray
a=np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
b = np.array([[1, 2], [3, 4]])
print(b)

[[1 2]
 [3 4]]


In [65]:
c = np.array([1, 2, 3], dtype=object)
print(c)
c

[1 2 3]


array([1, 2, 3], dtype=object)

In [38]:
d = np.array([1, 2, 3], dtype=complex)
print(d)
d

[1.+0.j 2.+0.j 3.+0.j]


array([1.+0.j, 2.+0.j, 3.+0.j])

In [14]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [15]:
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
#b = a.reshape(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [16]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [17]:
a.ndim


1

In [19]:
# now reshape it
b = a.reshape(2,4,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [21]:
x = np.array([1,2,3,4,5], dtype=np.int8)
print(x.itemsize)

1


In [22]:
x = np.array([1,2,3,4,5], dtype=np.float32)
print(x.itemsize)

4


In [23]:
x = np.array([1,2,3,4,5])
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [24]:
x = np.empty([3,2], dtype=int)
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [29]:
x = np.zeros((5,), dtype=int)
x

array([0, 0, 0, 0, 0])

In [30]:
z = np.zeros((2,2), dtype=[('x', 'i4'), ('y', 'i4')])
z

array([[(0, 0), (0, 0)],
       [(0, 0), (0, 0)]], dtype=[('x', '<i4'), ('y', '<i4')])

In [31]:
l = np.ones(5)
l

array([1., 1., 1., 1., 1.])

In [37]:
p = np.ones([2,2], dtype=int)
print(p)

[[1 1]
 [1 1]]


In [35]:
x = [1,2,3]
a = np.asarray(x)
print(a)

[1 2 3]


In [36]:
a

array([1, 2, 3])

In [39]:
x = [1,2,3]
a = np.asarray(x, dtype=float)
print(a)

[1. 2. 3.]


In [41]:
# ndarray from tuple
import numpy as np
x = (1,2,3)
a = np.asarray(x)
print(a)

[1 2 3]


In [42]:
# ndarray from list of tuples
import numpy as np
x = [(1,2,3),(4,5)]
a = np.asarray(x)
print(a)

[(1, 2, 3) (4, 5)]


C:\Users\ABIRAMI\anaconda3\lib\site-packages\numpy\core\_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)


In [52]:
import numpy as np

s = 'Hello World'
# Convert the string to a bytes-like object using the encode() method
b = s.encode('utf-8')
# Use the frombuffer() function to create a NumPy array from the bytes-like object
a = np.frombuffer(b, dtype='S1')
print(a)


[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


In [53]:
import numpy as np

s = 'Hello World'
a = np.array(list(s))
print(a)


['H' 'e' 'l' 'l' 'o' ' ' 'W' 'o' 'r' 'l' 'd']


In [59]:
# create list object using range function
import numpy as np
list = range(5)
print(list)


range(0, 5)


In [61]:
list = range(5)
it = iter(list)
# use iterator to create ndarray
x = np.fromiter(it, dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [62]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [63]:
# dtype set
x = np.arange(5, dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [64]:
y = np.arange(10,20,2)
print(y)

[10 12 14 16 18]
